version: '3.7'
services:
  gpu1:
    build:
      context: .
      dockerfile: dGPU.Dockerfile
    container_name: gpu1
    privileged: true
    network_mode: host
    devices:
      - /dev/dri
  gpu2:
    build:
      context: .
      dockerfile: dGPU2.Dockerfile
    container_name: gpu2
    privileged: true
    network_mode: host
    devices:
      - /dev/dri
